# Generated by Django 3.2.3 on 2021-06-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcontact',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='addcontact',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default=None, max_length=100),
        ),
    ]
