# Generated by Django 3.2.3 on 2021-06-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_detail', '0002_auto_20210626_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcontact',
            name='image',
            field=models.ImageField(default=None, upload_to='profile_picture'),
        ),
    ]
