# Generated by Django 3.2.3 on 2021-06-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_detail', '0003_addcontact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcontact',
            name='image',
            field=models.ImageField(default=None, upload_to='profile_picture/'),
        ),
    ]
